using System;
using System.Linq;
using System.Reflection;
using System.Collections;
using System.IO;
using Ostranauts.Trading;
using Phobos.Ostranauts.Framework.Construction;
using Phobos.Ostranauts.Framework.Registration;
using PhobosShipbreaker;
using PhobosShipbreaker.Core;

internal static class AssemblyNativeChecks
{
    internal static void Run(NativeDefinitions d, string repo, Action<bool,string> check)
    {
        // The one shared trigger hook (29 September 2026 pass) carries the section selectors as well as construction's.
        var selectionHook = typeof(SectionAssembly).Assembly.GetType("Phobos.Ostranauts.Framework.Construction.TriggerRefinementPatch")!
            .GetMethod("Postfix", BindingFlags.Static | BindingFlags.NonPublic)!;
        var informationHook = typeof(SectionAssembly).Assembly.GetType("Phobos.Ostranauts.Framework.Controls.ItemInformationAction")!
            .GetMethod("Prefix", BindingFlags.Static | BindingFlags.NonPublic)!;
        foreach (string? name in new string?[] { null, "", "UnrelatedNativeCondition" })
        foreach (bool result in new[] { false, true })
        {
            object?[] arguments = { new CondTrigger { strName = name! }, null, result };
            selectionHook.Invoke(null, arguments);
            check((bool)arguments[2]! == result, "Actual selection postfix preserves unnamed/unrelated native results without reading a target");
            check((bool)informationHook.Invoke(null, new object[] { new Interaction { strName = name! }, result })!,
                "Actual information prefix leaves unnamed/unrelated interactions to the game");
        }
        // Generated by Blue Bottle Games' actual Installables.Create against installed native templates.
        SectionAssembly.RetireFromMenu();
        var wholes = (IDictionary)typeof(SectionAssembly).GetField("Wholes", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)!;
        foreach (string prefix in new[] { Content.Prefix, ReclaimerRules.Prefix, FurnaceRules.Prefix })
        {
            var job = d.Installables[prefix + "SectionAssembly"];
            var contracts = (IDictionary)typeof(SectionAssembly).GetField("Jobs", BindingFlags.Static | BindingFlags.NonPublic)!.GetValue(null)!;
            var contract = contracts[job.strName]!;
            var appearance = (SectionAssemblyAppearance)contract.GetType().GetField("Appearance", BindingFlags.Instance | BindingFlags.NonPublic)!.GetValue(contract)!;
            check(appearance != null, "Production assembly opts into artwork: " + prefix);
            int size = prefix == FurnaceRules.Prefix ? 96 : 64;
            foreach (string path in new[] { appearance!.Early, appearance.Intermediate })
            foreach (string suffix in new[] { ".png", "Normal.png" })
            {
                byte[] png = File.ReadAllBytes(Path.Combine(repo, "mods/PhobosShipbreaker/images", path + suffix));
                int width = (png[16] << 24) | (png[17] << 16) | (png[18] << 8) | png[19];
                int height = (png[20] << 24) | (png[21] << 16) | (png[22] << 8) | png[23];
                check(width == size && height == size && appearance.Size == size, "Registered construction colour/normal retains native footprint: " + path + suffix);
            }
            var action = DataHandler.dictInteractions["ACT" + job.strName];
            check(action.aLootItms.Any(x => x.StartsWith("input,")), "Native site input contract replaces simultaneous actor removal: " + prefix);
            check(!action.aLootItms.Any(x => x.StartsWith("removeus,")), "Assembly does not require all sections in actor inventory");
            check(DataHandler.dictInteractions["ACT" + job.strName + "Allow"].CTTestThem == "TIsPlaceholder", "Native work targets construction marker");
            check(DataHandler.dictInteractions["MS" + job.strName].objLootModeSwitch == "Output" + job.strName, "Native completion uses installed output");
            check(job.aLootCOs.Single() == prefix + "Installed" && job.aToolCTsUse.SequenceEqual(new[]{"TIsToolMortorq","TIsToolSoldering"}), "Installed outcome and tool bill retained");
            var selector = d.Triggers[job.CTThem];
            check(selector.TriggeredDataCO(new DataCO(d.Objects[job.strActionCO]), false), "Native source condition accepts matching section");
            check(!selector.TriggeredDataCO(new DataCO(DataHandler.dictCOs["ItmScrapSteel"]), false), "Ordinary scrap cannot substitute for a section");
            // Shipbreaker 0.60.0: machines come whole; the section job stays only for saved sites.
            check(Installables.dictJobBuildOptionsListed["APPS"][prefix + "Installed"].strName == prefix + "LooseInstall" &&
                Installables.dictJobBuildOptions["APPS"][prefix + "Installed"].strName == prefix + "LooseInstall", "INSTALL deterministically chooses the whole machine");
            check(DataHandler.dictCOs[prefix + "Loose"].aInteractions.Contains("ACT" + prefix + "LooseInstall"), "Existing whole machinery keeps direct Install");
            check(!DataHandler.dictCOs[job.strActionCO].aInteractions.Contains("ACT" + job.strName) && DataHandler.dictInteractions.ContainsKey("ACT" + job.strName),
                "A section no longer starts a site, but saved sites keep their native action: " + prefix);
            var whole = wholes[prefix + "LooseInstall"]!;
            var wholeAppearance = (SectionAssemblyAppearance)whole.GetType().GetField("Appearance", BindingFlags.Instance | BindingFlags.NonPublic)!.GetValue(whole)!;
            check(ReferenceEquals(wholeAppearance, appearance) || wholeAppearance.Early == appearance.Early && wholeAppearance.Intermediate == appearance.Intermediate,
                "The whole machine's own Install site shows the same construction stages: " + prefix);
            check((string)whole.GetType().GetField("Section", BindingFlags.Instance | BindingFlags.NonPublic)!.GetValue(whole)! == prefix + "Loose",
                "Whole-machine stages follow the exact loose machine: " + prefix);
        }
        foreach (string prefix in new[] { FurnaceRules.Radiator, FurnaceRules.ThermalPort })
        foreach (string suffix in new[] { "Loose", "LooseDmg", "Installed", "InstalledDmg" })
        {
            var co = d.Objects[prefix + suffix];
            check(co.strContainerCT == CoolingCargo.RejectAll && co.aInteractions.Contains(CoolingCargo.Action), "Every cooling form retains explicit legacy recovery");
            var trigger = d.Triggers[co.strContainerCT];
            foreach (string id in new[] { "ItmScrapSteel", "ItmScrapTrash" })
                check(!trigger.TriggeredDataCO(new DataCO(DataHandler.dictCOs[id]), false), "New solid deposits rejected");
            check(!trigger.TriggeredDataCO(new DataCO(new JsonCondOwner {aStartingConds=Array.Empty<string>()}),false), "Nonsolid deposits also rejected");
            check(co.aSlotsWeHave.Length == 0 && co.strLoot == "Blank", "Recovery does not spawn contents or hidden compartments");
        }
        check(!DataHandler.dictConds["StatMass"].bPersists, "Native section-to-machine mode switch takes output mass rather than section mass");
        var calls = PlaceholderLoadChecks.Calls(typeof(Placeholder).GetMethod(nameof(Placeholder.Cancel))!);
        check(calls.Any(m => m.Name == "GetLotCOs") && calls.Any(m => m.Name == "RemoveLotCO") && calls.Any(m => m.Name == "DropCO"), "Native cancellation releases staged material through its existing drop path");
        check(typeof(JsonPlaceholder).GetProperty("strInstallIA") != null && typeof(JsonPlaceholder).GetProperty("strActionCO") != null,
            "Native save DTO preserves exact assembly action and source identity");
        var spawn = typeof(Ship).GetMethod("SpawnItems", BindingFlags.Instance|BindingFlags.NonPublic)!;
        check(PlaceholderLoadChecks.Calls(spawn).Any(m => m.Name == "AddCOSimple"), "Native loading restores legacy children without applying new-deposit admission");
        check(typeof(Container).GetMethod(nameof(Container.AllowedCO))!.GetParameters().Single().Name == "coIn", "Recovery transition Harmony binding matches installed runtime");
        var create = typeof(DataHandler).GetMethod(nameof(DataHandler.GetCOPlaceholder))!;
        check(PlaceholderLoadChecks.Calls(create).Any(m => m.DeclaringType == typeof(Item) && m.Name == "SetData"), "Native placeholder initializes the retained Item before appearance attachment");
        var refresh = typeof(SectionAssemblyView).GetMethod("Refresh", BindingFlags.Instance | BindingFlags.NonPublic)!;
        var appearanceCalls = PlaceholderLoadChecks.Calls(refresh);
        check(!appearanceCalls.Any(m => m.Name == "SetAlt" || m.Name == "SetCondAmount" || m.Name == "ModeSwitch"), "Appearance refresh does not use global alternate-material cache or mutate native work/identity");
        var cancel = PlaceholderLoadChecks.Calls(typeof(Placeholder).GetMethod(nameof(Placeholder.Cancel))!);
        check(typeof(Placeholder).GetMethod(nameof(Placeholder.Cancel))!.GetParameters().Single().ParameterType == typeof(CondOwner) &&
            cancel.Any(m => m.Name == "Destroy"), "Legacy-site cancellation binds the game's own one-argument cancel, which retires the marker");
        var drop = typeof(Ship).GetMethod(nameof(Ship.DropCO), new[] { typeof(CondOwner), typeof(UnityEngine.Vector2) });
        check(drop != null && drop.ReturnType == typeof(CondOwner) && PlaceholderLoadChecks.Calls(drop).Any(m => m.Name == "DropCOsNearby"),
            "Converted parts use the game's own nearby deck drop, returning anything left over");
    }

    /// <summary>Shipbreaker 0.60.0: the retired sections convert from the recipe pack actually registered in game.</summary>
    internal static void Conversions(Action<bool,string> check)
    {
        var logs = new System.Collections.Generic.List<string>();
        var stations = DataHandler.dictCOs.Values.Where(c => c.aInteractions != null).ToDictionary(c => c, c => c.aInteractions.ToArray());
        try
        {
            AssemblyDefinitions.FinishRegistration(logs.Add);
            check(logs.Count == 0, "Every retired section registers its conversion: " + string.Join("; ", logs));
            foreach (var spec in AssemblyDefinitions.Specs)
            {
                var rule = Phobos.Ostranauts.Framework.Persistence.LegacyItemConversions.Rules.SingleOrDefault(r => r.RetiredId == spec.Section);
                check(rule != null && rule.SetSize == spec.Count && rule.WholeId == spec.Prefix + "Loose", "Complete section sets become the whole loose machine: " + spec.Section);
                if (rule == null) continue;
                check(Math.Abs(EquipmentSaveUpgrade.Amount(DataHandler.dictCOs[rule.WholeId].aStartingConds, "StatMass") - rule.WholeKg) < 1e-9 &&
                    Math.Abs(EquipmentSaveUpgrade.Amount(DataHandler.dictCOs[spec.Section].aStartingConds, "StatMass") - rule.UnitKg) < 1e-9,
                    "Conversion masses match the live definitions: " + spec.Section);
                check(rule.Materials.All(m => DataHandler.dictCOs.TryGetValue(m.Id, out var co) &&
                    Math.Abs(EquipmentSaveUpgrade.Amount(co.aStartingConds, "StatMass") - m.UnitKg) < 1e-9) &&
                    Math.Abs(rule.Materials.Sum(m => m.Count * m.UnitKg) - spec.SectionKg) < 1e-9,
                    "A leftover returns its exact standard bill of native materials: " + spec.Section);
            }
            foreach (string recipe in AssemblyDefinitions.RetiredSectionRecipes.Concat(AssemblyDefinitions.Legacy))
                check(!DataHandler.dictCOs.Values.Any(c => c.aInteractions?.Contains(RecipeRules.ActionId(recipe)) == true) &&
                    DataHandler.dictInteractions.ContainsKey(RecipeRules.ActionId(recipe)), "Retired recipe leaves every table but keeps its saved-queue action: " + recipe);
            check(DataHandler.dictCOs.Values.Any(c => c.aInteractions?.Contains(RecipeRules.ActionId("PhobosBuildHullChute")) == true), "Other Shipbreaker recipes stay on the tables");
        }
        finally
        {
            // Later checks read the same native definitions.
            foreach (var pair in stations) pair.Key.aInteractions = pair.Value;
        }
    }
}
