using System;
using System.Linq;
using System.Reflection;
using Ostranauts.Trading;
using Phobos.Ostranauts.Framework.Construction;
using Phobos.Ostranauts.Framework.Registration;
using PhobosShipbreaker;
using PhobosShipbreaker.Core;

internal static class AssemblyNativeChecks
{
    internal static void Run(NativeDefinitions d, Action<bool,string> check)
    {
        var selectionHook = typeof(SectionAssembly).Assembly.GetType("Phobos.Ostranauts.Framework.Construction.SectionAssemblySelection")!
            .GetMethod("Postfix", BindingFlags.Static | BindingFlags.NonPublic)!;
        var informationHook = typeof(SectionAssembly).Assembly.GetType("Phobos.Ostranauts.Framework.Controls.ItemInformationAction")!
            .GetMethod("Prefix", BindingFlags.Static | BindingFlags.NonPublic)!;
        foreach (string? name in new string?[] { null, "", "UnrelatedNativeCondition" })
        foreach (bool result in new[] { false, true })
        {
            object?[] arguments = { new CondTrigger { strName = name! }, null, result };
            selectionHook.Invoke(null, arguments);
            check((bool)arguments[2]! == result, "Actual selection postfix preserves unnamed/unrelated native results without reading a target");
            check((bool)informationHook.Invoke(null, new object[] { new Interaction { strName = name! }, result })!,
                "Actual information prefix leaves unnamed/unrelated interactions to the game");
        }
        // Generated by Blue Bottle Games' actual Installables.Create against installed native templates.
        SectionAssembly.PreferAssemblyMenu();
        foreach (string prefix in new[] { Content.Prefix, ReclaimerRules.Prefix, FurnaceRules.Prefix })
        {
            var job = d.Installables[prefix + "SectionAssembly"];
            var action = DataHandler.dictInteractions["ACT" + job.strName];
            check(action.aLootItms.Any(x => x.StartsWith("input,")), "Native site input contract replaces simultaneous actor removal: " + prefix);
            check(!action.aLootItms.Any(x => x.StartsWith("removeus,")), "Assembly does not require all sections in actor inventory");
            check(DataHandler.dictInteractions["ACT" + job.strName + "Allow"].CTTestThem == "TIsPlaceholder", "Native work targets construction marker");
            check(DataHandler.dictInteractions["MS" + job.strName].objLootModeSwitch == "Output" + job.strName, "Native completion uses installed output");
            check(job.aLootCOs.Single() == prefix + "Installed" && job.aToolCTsUse.SequenceEqual(new[]{"TIsToolMortorq","TIsToolSoldering"}), "Installed outcome and tool bill retained");
            var selector = d.Triggers[job.CTThem];
            check(selector.TriggeredDataCO(new DataCO(d.Objects[job.strActionCO]), false), "Native source condition accepts matching section");
            check(!selector.TriggeredDataCO(new DataCO(DataHandler.dictCOs["ItmScrapSteel"]), false), "Ordinary scrap cannot substitute for a section");
            check(Installables.dictJobBuildOptionsListed["APPS"][prefix + "Installed"].strName == job.strName, "INSTALL deterministically chooses site assembly");
            check(DataHandler.dictCOs[prefix + "Loose"].aInteractions.Contains("ACT" + prefix + "LooseInstall"), "Existing whole machinery keeps direct Install");
        }
        foreach (string prefix in new[] { FurnaceRules.Radiator, FurnaceRules.ThermalPort })
        foreach (string suffix in new[] { "Loose", "LooseDmg", "Installed", "InstalledDmg" })
        {
            var co = d.Objects[prefix + suffix];
            check(co.strContainerCT == CoolingCargo.RejectAll && co.aInteractions.Contains(CoolingCargo.Action), "Every cooling form retains explicit legacy recovery");
            var trigger = d.Triggers[co.strContainerCT];
            foreach (string id in new[] { "ItmScrapSteel", "ItmScrapTrash" })
                check(!trigger.TriggeredDataCO(new DataCO(DataHandler.dictCOs[id]), false), "New solid deposits rejected");
            check(!trigger.TriggeredDataCO(new DataCO(new JsonCondOwner {aStartingConds=Array.Empty<string>()}),false), "Nonsolid deposits also rejected");
            check(co.aSlotsWeHave.Length == 0 && co.strLoot == "Blank", "Recovery does not spawn contents or hidden compartments");
        }
        check(!DataHandler.dictConds["StatMass"].bPersists, "Native section-to-machine mode switch takes output mass rather than section mass");
        var calls = PlaceholderLoadChecks.Calls(typeof(Placeholder).GetMethod(nameof(Placeholder.Cancel))!);
        check(calls.Any(m => m.Name == "GetLotCOs") && calls.Any(m => m.Name == "RemoveLotCO") && calls.Any(m => m.Name == "DropCO"), "Native cancellation releases staged material through its existing drop path");
        check(typeof(JsonPlaceholder).GetProperty("strInstallIA") != null && typeof(JsonPlaceholder).GetProperty("strActionCO") != null,
            "Native save DTO preserves exact assembly action and source identity");
        var spawn = typeof(Ship).GetMethod("SpawnItems", BindingFlags.Instance|BindingFlags.NonPublic)!;
        check(PlaceholderLoadChecks.Calls(spawn).Any(m => m.Name == "AddCOSimple"), "Native loading restores legacy children without applying new-deposit admission");
        check(typeof(Container).GetMethod(nameof(Container.AllowedCO))!.GetParameters().Single().Name == "coIn", "Recovery transition Harmony binding matches installed runtime");
    }
}
