"""Render/check the complete handling ledger from maintained native item evidence."""
import argparse
from collections import Counter
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/development/item-handling-audit.md"


def findings(item):
    result = []
    container = item["container"]
    recovery = container["trigger"] == "PhobosCoolingNoNewCargo" and "PhobosCoolingRecoverCargo" in item.get("actions", [])
    if container["trigger"] is not None and not container["inventoryAction"] and not recovery and "IsSystem" not in item["handlingFlags"]:
        result.append("H01: inaccessible container")
    if item["stackLimit"] > 1 and any(j["kind"] == "dismantle" for j in item["jobs"]):
        result.append("H02: split stack before dismantling")
    return result


def guard(mod, item):
    identity = item["id"]
    if "IsSystem" in item["handlingFlags"]:
        return "Internal feed; access through owning machine; intentionally no standalone actions."
    if mod == "PhobosAutoNav":
        return "Native module slots and service context; no floor INSTALL." if item["jobs"] else "Portable material; no equipment controls or further recipe."
    if identity.startswith(("PhobosFurnaceRadiator", "PhobosFurnaceThermalPort")):
        return "Cooling temperature, saved-state protection, contents and paired endpoint gate removal; heat/protection gate service. Explicit local legacy-cargo recovery; new deposits blocked. Maintenance information explains the current blocker."
    if identity in ("PhobosFurnaceInstalled", "PhobosFurnaceInstalledDmg", "PhobosFurnaceLoose", "PhobosFurnaceLooseDmg"):
        return "Cool, idle, unprotected, empty feed/products and drained managed coolant; paired cooling safety also applies."
    if mod == "PhobosAgriculture" and item["jobs"] and "WaterConduit" not in identity:
        return "R3 must be drained and unlinked; other appliances must clear retained contents, protected records and active work. Damaged panels remain for inspection/recovery."
    if any(j["kind"] == "dismantle" for j in item["jobs"]):
        return "Dismantle requires no cargo or pending lot (empty internal feed allowed where registered); native placement, tools and condition gates remain."
    if any(a.startswith("SeekFood") for a in item.get("actions", [])):
        return "Native eating/hunger actions retained; handheld food, no repair or equipment controls."
    return "Portable supply/byproduct or bulky housing; use through owning machine/recipe, not invented local machine actions."


def validate(data):
    identities = [i["id"] for m in data["mods"] for i in m["items"]]
    if len(identities) != len(set(identities)):
        raise ValueError("Duplicate item evidence")
    for mod in data["mods"]:
        for item in mod["items"]:
            if item["missingDirectActions"]:
                raise ValueError("Missing direct action: " + item["id"])
            for job in item["jobs"]:
                if not job["generated"] or not job["attached"] or job["targetPassWithWear"] is not True:
                    raise ValueError("Incomplete native maintenance registration/target: " + job["id"])
                expected = job["kind"] != "restore"
                if job["targetPassOnFreshDefinition"] != expected:
                    raise ValueError("Unexpected pristine target result: " + job["id"])


def render(data):
    validate(data)
    rows, counts = [], Counter()
    jobs = [j for m in data["mods"] for i in m["items"] for j in i["jobs"]]
    for mod in data["mods"]:
        for item in mod["items"]:
            flags = set(item["handlingFlags"])
            category = "internal" if "IsSystem" in flags else "installed" if item["installed"] else "cumbersome" if "IsCumbersome" in flags else "portable"
            counts[category] += 1
            actions = ", ".join(item["actions"]) or "—"
            work = ", ".join(sorted(set(j["kind"] for j in item["jobs"]))) or "—"
            issues = "; ".join(findings(item)) or "No additional definition fault found"
            rows.append(f"| {mod['id']} | `{item['id']}` | {category}; {', '.join(item['slots']) or 'no carry slots'} | {actions} | {work} | {issues}. {guard(mod['id'], item)} |")
    return "\n".join([
        "# Item handling and action audit", "",
        "Reviewed 27 September 2026 and updated 28 September after implementing the approved corrections. Generated by `scripts/audit-item-handling.py` from the maintained native export. Offline fixes are distinct from outstanding owner Unity validation; see [assembly and maintenance](../section-assembly-and-maintenance.md).", "",
        "## Coverage and result", "",
        f"All **{len(rows)} implemented definitions** across five mods: " + "; ".join(f"{m['id']}: {len(m['items'])}" for m in data['mods']) + ". Manufacturing has no implemented objects and remains held.", "",
        f"Handling inventory: {counts['installed']} installed forms, {counts['cumbersome']} cumbersome loose forms/sections/housings, {counts['portable']} portable boards/supplies/materials/foods, and {counts['internal']} internal feed compartments. Intact and damaged forms are counted separately.", "",
        f"All **{len(jobs)} native service/installation jobs** were run through Blue Bottle Games' actual data-only `Installables.Create` generator, not merely counted in our source. Every resulting action exists and is attached to its object. All direct action IDs resolve. Every maintenance target passes with appropriate wear; the 35 Restore targets correctly fail on pristine definitions and pass with wear. These checks do not run Unity interaction queues or grant the worker tools/access.", "",
        "## Ranked findings", "",
        "### H01 — High: inaccessible inventories on F6-P and F6-R (fixed offline)", "",
        "At the original audit, all eight installed/loose/intact/damaged definitions for the thermal exhaust port and exterior radiator retained `strContainerCT=TIsFitContainerSolid`, inherited from their machine template. Their container flag, grid dimensions and Inventory action were removed, but the container trigger was not. Native `CondOwner.SetData` creates a container when that trigger is non-null. Removing only the flag and grid therefore did not remove storage.", "",
        "The read-only owner-save check confirms nine direct cargo objects in the installed F6-P, comprising 22 saved units after following their stacks: 10 coolant charges, eight irrigation charges, three treatment cartridges and one seed-potato item. The audited version had no Inventory action or local recovery route. Several cargo records retain native lot flags. The save establishes current contents, not how or when they entered.", "",
        "The reported port was cold (about 1.8 C from its saved heat record), had current maintenance maxima and the economy marker, and had small ordinary wear. Its contents independently trigger both the generic dismantling refusal and the furnace removal refusal. That explains Uninstall and Dismantle disappearing while Restore remains possible; Restore does not require empty contents. The installed radiator in this save has no corresponding cargo, but shares the defective definitions.", "",
        "The inconsistent container setup is already present in furnace introduction commit `6adb3f2`; this is not evidence of a recent Auto Nav regression. **Implemented correction:** Recover stored cargo opens checked local recovery without relocating cargo. A reject-all recovery receptacle preserves native restoration of saved children while blocking new deposits. Actual work lots remain reserved; stale orphan lot markers are cleared only on explicit safe recovery. Native damage transitions retain only captured cargo in the same cooling family. Do not simply clear `strContainerCT` on load or weaken the empty-machine guards: that risks orphaning cargo or destroying it during maintenance. Test new, saved, installed, loose and damaged forms before delivery.", "",
        "Source: [cooling definitions](../../src/PhobosShipbreaker/FurnaceDefinitions.cs), [removal/service checks](../../src/PhobosShipbreaker/FurnaceOperations.cs), [local maintenance panel](../../src/PhobosShipbreaker/IndustrialPanel.cs), [shared cargo guard](../../src/PhobosFramework/Registration/MaintenanceSafety.cs).", "",
        "### H02 — Medium: stacked conduit maintenance has poor explanation (existing limitation)", "",
        "Four loose conduit forms—intact/damaged F6-C and intact/damaged Agriculture irrigation—support stacks and dismantling. Native `GetCOsSafe` traverses stack members as well as cargo. The shared empty-item test therefore refuses a stack head with other pieces attached. Existing item guides already say to split a section for individual work; this audit does not establish a new regression. The old generic failure text poorly explained an ordinary pipe stack. Framework now supplies a specific split-stack reason and a Maintenance information action. Separate one piece before dismantling; the new explanation retains that restriction. Do not relax destruction checks without proving that the other pieces survive.", "",
        "Source: [shared guard](../../src/PhobosFramework/Registration/MaintenanceSafety.cs), [construction's explicit distinction between stacks and cargo](../../src/PhobosFramework/Construction/ConstructionHooks.cs), [reviewed item-reference inputs](../../config/item-reference.json).", "",
        "### H03 — Medium: hidden safety actions are hard to diagnose (presentation gap)", "",
        "Furnace/cooling equipment can hide removal for heat, coolant, contents, protected state or an unsafe paired endpoint. Agriculture can hide removal for crops, water/solution/line parcels, a cooking/workup job, protected state, or an R3 link. The generic dismantling guard also rejects saved lots and cargo. These are legitimate safety restrictions, but a missing button and broad message do not tell the player which condition applies. Implemented read-only local Maintenance information, with specific furnace/Agriculture blockers and recovery instructions. Preserve command-time checks and keep remote inventory access restricted.", "",
        "Source: [Agriculture guards](../../src/PhobosAgriculture/Plugin.cs), [furnace guards](../../src/PhobosShipbreaker/FurnaceOperations.cs), [shared guards](../../src/PhobosFramework/Registration/MaintenanceSafety.cs).", "",
        "### H04 — High: final assembly conflicts with cumbersome sections (fixed offline)", "",
        "D4-S is an unfinished construction section, not an installed D4 fixture. The initial audit correctly identified its drag-only handling, but its table-recipe advice missed a workflow conflict: completion selects all material from the actor, while the native drag slot holds one nonstackable section and final assembly needs two or three. The approved correction adds native section construction sites and Assembly information. INSTALL > APPS chooses those sites; whole loose machines retain direct Install. Old table actions remain resolvable for saved queues but are no longer offered for new jobs. Existing hand/container placement is preserved until released. [Native site contracts](../../src/PhobosFramework/Construction/SectionAssembly.cs) and [content bills](../../src/PhobosShipbreaker/AssemblyDefinitions.cs) preserve section masses, stage lots separately and validate the exact full bill before completion.", "",
        "Historical evidence: the earlier held 80 kg D4-S lacked IsCumbersome, inherited from the initial prototype `cd207fa`. The prior correction added explicitly registered bulky flags during detached save loading, without moving cargo. The latest read-only archive check finds **524 matching saved objects across 24 represented definitions/aliases**, with no missing expected installed/cumbersome/internal flags. This includes the pictured section with IsCumbersome present. This is stronger evidence than the earlier definition-only ledger, but does not verify live drag animations or every saved object in every save.", "",
        "## Decisions for the remaining items", "",
        "Installed equipment has no carry slots or pickup actions; loose bulky machines and declared heavy sections/housings use drag. Compact boards, pipes, food and supplies retain hand handling. No arbitrary universal weight cutoff was added. Auto Nav boards use native module slots rather than floor INSTALL. Three internal feed bins remain inaccessible as independent cargo and use their owning machine's feed access. Damaged panels remain available for inspection, draining and recovery while operational services reject unsafe work. Raw potatoes, seeds and industrial supplies are not given eating or machine-control actions; the cooked meal and lettuce retain native food actions. Legacy residue and terminal waste receive no invented processing/repair recipes.", "",
        "Repair of a broken form and Restore of ordinary wear are separate native jobs. Restore is correctly absent at zero wear. Native tools, crew capability, reach, locked/contained state, work materials and placement can further affect menus. Generated target checks retain existing differences: some appliance Install/Repair targets allow contained items, whereas native not-contained targets reject them; target admission alone is not a live-menu verdict. Bash is a native contextual action, not an extra Phobos machine command or a substitute for Uninstall.", "",
        "The audit also reviewed additive Phobos actions on objects owned elsewhere: table construction, terminal study, and optional recycler capture. [Construction registration](../../src/PhobosFramework/Construction/ConstructionRegistry.cs) and [terminal study registration](../../src/PhobosFramework/Crew/CrewSpecialities.cs) append actions while retaining the existing lists. Agriculture similarly appends capture controls only when its adapter for [Valtora’s Ship’s Water](https://steamcommunity.com/sharedfiles/filedetails/?id=3757331189) is available; [capture commands](../../src/PhobosAgriculture/RecyclerCapture.cs) retain access and saved-state checks. These external objects are not counted as new Phobos definitions. This source review is not a full audit or live compatibility test of other authors’ mods.", "",
        "## Evidence, scope and verification limits", "",
        "Primary source: **Blue Bottle Games' installed Ostranauts 1.0.1.5 definitions and code**, inspected locally, not redistributed. [Official Ostranauts page](https://store.steampowered.com/app/1022980/Ostranauts/). Native `Installables.Create`, `CondOwner.SetData`, `CondOwner.VisitCOs`, save parent references and published mod definitions support the findings. The export records the native assembly hash and source fingerprints. Repository links identify our code; the official link identifies the game, not a public copy of its internal implementation.", "",
        "The reusable read-only `scripts/audit-saved-item-actions.py` scans serialized ship objects, resolves module aliases and follows cargo stack IDs; keep its output under ignored local evidence. It does not inspect live worker access or rewrite saves. Data-only native generation checks and existing regression suites establish offline contracts. Full Unity menu visibility, cargo recovery, slot transitions, third-party patches and maintenance completion remain owner-tested. The original audit changed no gameplay code or saves. The 28 September follow-up implements the fixes described above; source versions are Framework 0.31.0, Shipbreaker 0.31.0 and Agriculture 0.16.1. Save files remain unedited; build/install status belongs to the delivery report.", "",
        "## Complete per-definition ledger", "",
        "Every row was reviewed against its family role, generated jobs, container access and runtime guards. 'No additional definition fault found' is deliberately narrower than gameplay approval. The maintained JSON also records each generated action, attachment, target trigger and fresh/worn/contained target result. Corrections above are checked offline; native live interaction remains owner-tested.", "",
        "| Mod | Definition | Handling and slots | Direct actions | Generated maintenance | Review and contextual limits |",
        "|---|---|---|---|---|---|", *rows, ""
    ])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(json.loads((ROOT / "docs/item-reference-data.json").read_text(encoding="utf-8")))
    if args.check:
        if not REPORT.exists() or REPORT.read_text(encoding="utf-8") != content:
            raise SystemExit("Item handling ledger is stale")
    else:
        REPORT.write_text(content, encoding="utf-8", newline="\n")
    print("Item handling ledger checked" if args.check else "Item handling ledger written")


if __name__ == "__main__":
    main()
