"""Render/check the complete handling ledger from maintained native item evidence."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/item-handling-audit.md"
def render(data):
    rows=[]
    for mod in data["mods"]:
        for item in mod["items"]:
            flags=set(item["handlingFlags"])
            category="internal compartment" if "IsSystem" in flags else "installed" if item["installed"] else "cumbersome" if "IsCumbersome" in flags else "portable"
            actions=", ".join(item["actions"]) or "—"
            work=", ".join(sorted(set(j["kind"] for j in item["jobs"] if j.get("kind")))) or "—"
            rows.append(f"| {mod['id']} | `{item['id']}` | {category} | {', '.join(item['slots']) or '—'} | {actions} | {work} |")
    return "\n".join([
        "# Item handling and action audit", "", "Reviewed 27 September 2026. Generated by `scripts/audit-item-handling.py` from the native-definition export maintained with the item references.", "",
        "## Findings and correction", "",
        "The D4-S screenshot shows a construction section, not a D4 machine. Its definition inherited scrap-metal hand attachments and pickup/stack actions without a cumbersome flag. The same gap affects R4-S and F6-S sections. D4-S inheritance was already present in the initial prototype commit `cd207fa`; inspection does not establish a regression in the recent Auto Nav releases.", "",
        "Loose machinery families also omitted native pickup/drop actions, while small conduit parts retained drag-only attachments. Shared normalization now retains functional actions, adds transport actions to loose cargo, removes carry slots from installed items, and offers stack actions only where stacking exists. Damaged R3 reservoirs no longer offer operating work. Native repair, restore, uninstall, dismantle, food and module-slot actions remain governed by their existing conditions.", "",
        "D4-S/R4-S/F6-S sections, loose machines, and large Firstlight/R3 housing remains are cumbersome. Small parts, boards, supplies, meals and compact material packets remain portable. This is an explicit content classification, not a new universal mass cutoff. Sections are table-recipe inputs, not INSTALL fixtures; the audit does not invent controls or repair jobs for unfinished components. Manufacturing has no implemented items and remains held.", "",
        "## Save and native evidence", "",
        "The latest owner autosave was read without modification. It contains an 80 kg D4-S held in a hand and R4-S/F6-S sections in containers; the saved section conditions lack IsCumbersome. Current logs confirm the previous Framework 0.30.1, Shipbreaker 0.29.1, Agriculture 0.15.2 and Auto Nav 0.22.2 loaded. No relevant Phobos registration failure explains the handling gap. Other-provider log errors are not attributed as its cause.", "",
        "Primary source: **Blue Bottle Games’ installed Ostranauts 1.0.1.5 definitions and code**, inspected locally and not redistributed. [Official Ostranauts page](https://store.steampowered.com/app/1022980/Ostranauts/). Native cumbersome appliances still use the label Pick Up with a drag-only slot map. IsCumbersome excludes ordinary solid containers. CondOwner.SetData restores explicit saved conditions instead of new defaults; Slots.SlotItem rejects missing slot mappings. Accordingly the correction adds only explicitly registered bulky flags to detached load data, preserves saved locations and cargo, and temporarily restores an existing saved hand mapping until native unslot succeeds. Once released, only drag remains. Existing contained items can be removed without forced relocation. No save file, identity, mass, wear, value or work progress is rewritten.", "",
        "## Verification and limits", "",
        "Native-definition tests check transport/stack/slot membership across all implemented items, internal and installed exclusions, retained dismantling, non-transport food actions, exact saved-state preservation, idempotence, compressed defaults, unrelated-item isolation and the native release-hook signature. Existing construction, maintenance, material-accounting and native-boundary suites remain required. Table actions are definition entries: their visibility still depends on native context, tools, damage and placement. The screenshot's exact missing Drop menu has not been reproduced in Unity; the saved held section should satisfy the unchanged native carried-item trigger. Third-party menu patches and transient live context remain possible additional causes if it recurs.", "",
        "Owner check: load the existing save, verify sections and their contents are intact, put a previously held section down, then pick it up into drag. Check a loose machine's pickup/drop and installation; uninstall before moving installed equipment. Check damaged equipment maintenance, portable conduit parts, board slots, stacked supplies and meal eating. Live menu rendering, slot transitions and construction after reload remain unverified until owner testing.", "",
        f"## Complete ledger — {len(rows)} definitions", "",
        "Direct action IDs below exclude maintenance actions generated later by native installable registration; those jobs are listed separately. Internal compartments and held Manufacturing are intentional exceptions.", "",
        "| Mod | Definition | Handling | Slots | Direct actions | Maintenance jobs |",
        "|---|---|---|---|---|---|", *rows, ""
    ])
def main():
    parser=argparse.ArgumentParser();parser.add_argument("--check",action="store_true");args=parser.parse_args()
    content=render(json.loads((ROOT/"docs/item-reference-data.json").read_text(encoding="utf-8")))
    if args.check:
        if not REPORT.exists() or REPORT.read_text(encoding="utf-8")!=content: raise SystemExit("Item handling ledger is stale")
    else: REPORT.write_text(content,encoding="utf-8",newline="\n")
    print("Item handling ledger checked" if args.check else "Item handling ledger written")
if __name__=="__main__":main()
