#!/usr/bin/env python3
"""Render player item guides from a native audit snapshot and reviewed explanations."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = Path('docs/item-reference-data.json')
CONFIG = Path('config/item-reference.json')
SLUGS = {'PhobosAutoNav': 'auto-nav', 'PhobosShipbreaker': 'shipbreaker',
         'PhobosAgriculture': 'agriculture', 'PhobosFramework': 'framework',
         'PhobosApproachAssist': 'approach-assist', 'PhobosManufacturing': 'manufacturing'}


def source_hashes(root):
    paths = set()
    for base in ('src', 'mods', 'translations'):
        for path in (root / base).rglob('*'):
            if path.is_file() and not {'bin', 'obj'}.intersection(path.parts) and path.suffix in ('.cs', '.csproj', '.json'):
                paths.add(path)
    paths.update(root / p for p in ('tests/PhobosNative.Tests/ItemReferenceExport.cs',
                                  'tests/PhobosNative.Tests/EquipmentValueAudit.cs',
                                  'tests/PhobosNative.Tests/Program.cs'))
    # Normalize line endings so a Windows export is verifiable on Linux CI.
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_text(encoding='utf-8-sig').replace('\r\n', '\n').encode()).hexdigest()
            for p in sorted(paths)}


def money(value):
    return f'{value:,.2f}'


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', ' ')


def table(headers, rows):
    return ['| ' + ' | '.join(headers) + ' |', '| ' + ' | '.join('---' for _ in headers) + ' |'] + [
        '| ' + ' | '.join(cell(v) for v in row) + ' |' for row in rows] + ['']


def validate(data, config):
    if data.get('schemaVersion') != 1 or config.get('schemaVersion') != 1:
        raise ValueError('Unsupported item-reference schema')
    mods = {m['id']: m for m in data['mods']}
    if len(mods) != len(data['mods']) or set(mods) != set(config['mods']) or set(mods) != set(SLUGS):
        raise ValueError('Mod inventory changed: update the exporter and reviewed catalogue')
    for mid, mod in mods.items():
        actual = [i['id'] for i in mod['items']]
        declared = []
        keys = set()
        for group in config['mods'][mid]['groups']:
            if not re.fullmatch('[a-z0-9-]+', group['key']) or group['key'] in keys:
                raise ValueError(f'{mid}: duplicate/invalid section key')
            keys.add(group['key'])
            for field in ('title', 'function', 'use', 'find'):
                if not group.get(field, '').strip():
                    raise ValueError(f'{mid}/{group["key"]}: missing {field}')
            declared.extend(group['ids'])
        if len(actual) != len(set(actual)) or len(declared) != len(set(declared)):
            raise ValueError(f'{mid}: duplicate item coverage')
        if set(actual) != set(declared):
            raise ValueError(f'{mid}: explain new items {sorted(set(actual)-set(declared))}; remove stale entries {sorted(set(declared)-set(actual))}')
        for item in mod['items']:
            if item['massKg'] < 0 or item['baseValue'] < 0:
                raise ValueError(f'Invalid economic values for {item["id"]}')
        known = set(actual) | {a for i in mod['items'] for a in i['aliases']}
        if any(s['item'] not in known for s in mod['sources']):
            raise ValueError(f'{mid}: acquisition record has no documented item')
    return mods


def material(expression, config):
    key, amount = expression.split('=')
    chance, count = amount.split('x')
    if float(chance) != 1:
        raise ValueError('Probabilistic service input needs explicit documentation')
    return f'{float(count):g} × {config["triggers"][key]}'


def render(mod, notes, config):
    mid = mod['id']; items = {i['id']: i for i in mod['items']}
    out = [f'# {mod["name"]}: equipment and item reference', '',
           '<!-- Generated by scripts/update-item-reference.ps1. Edit config/item-reference.json, not this file. -->', '',
           f'Current source candidate: **{mod["version"]}**. Game target: **{mod["gameTarget"]}**. '
           'Values below come from offline definitions; they do not establish installation, gameplay validation or a live merchant quote.', '',
           notes['intro'], '',
           '**Reading prices:** credits per complete object at the stated condition, before shop margins, market effects, negotiation and extra wear. '
           'Pristine retail can cost more. Mass is the empty/dry definition or fresh commodity template; saved contents and variable recovery packets can weigh differently. '
           'Dismantle value is the sum of all listed outputs at base value, excluding labour and tools.', '',
           '**Repair and Restore:** Repair fixes a damaged form and retains the actual consumed service materials as spent parts. '
           'Restore reduces wear on functional equipment in place; it does not grant pristine status. '
           'Empty cargo and follow the machine’s local maintenance guards first. Work speed depends on crew, tools and current condition.', '',
           '**Finding stock:** the generated percentages are defaults per eligible native stock/loot roll, not per ship or guaranteed shop availability. '
           'Offers are additive, may be independent, and require normal restocking. Merchant offers request the listed finite lot when successful; separate world-loot branches retain their own listed quantities. '
           'Configuration, capacity and native generation rules still apply; loading an existing save does not refill its inventories.', '']
    if not mod['items']:
        out = out[:8]
    if mid == 'PhobosApproachAssist':
        out += ['The general maintenance explanation above describes current content mods. N0 instead retains its historical native-motherboard inheritance; its prototype exceptions are described below.', '']
    if notes['groups']:
        out += ['## Find an item', ''] + [f'- [{g["title"]}](#{g["key"]})' for g in notes['groups']] + ['']
    for group in notes['groups']:
        covered = [items[k] for k in group['ids']]
        out += [f'<a id="{group["key"]}"></a>', '', f'## {group["title"]}', '', group['function'], '',
                '**Use:** ' + group['use'], '', '**Where it appears:** ' + group['find'], '']
        tabs = sorted({i['installTab'] for i in covered if i['installTab']})
        out += ['**Placement:** ' + ('INSTALL → ' + ', '.join(tabs) + '. Obtain the loose item first; the menu does not manufacture it.' if tabs else
                'Built into its parent machine; not separately installable.' if group['internal'] else
                'Inventory/module-slot item; no standalone INSTALL entry.'), '']
        modes = [mode for item in covered for mode in item.get('operatingModes', [])]
        if modes:
            out += table(['Operating mode (functional, installed)', 'Powered seconds', 'Demand (kW)', 'Nominal work energy (kWh)'],
                         [(m['name'], f"{m['seconds']:g}", f"{m['kw']:g}", f"{m['seconds'] * m['kw'] / 3600:.4f}") for m in modes])
            out += ['Authored default work values. Cutting captures its duration and demand per started wall; partial delivered electricity earns proportional progress. Modes run sequentially. D4/R4 work and idle consumption are additional.', '']
        if group['notes']:
            out += [group['notes'], '']
        if group['guide']:
            out += [f'Full operating instructions: [{group["title"]} guide]({group["guide"]}).', '']
        if group['internal']:
            out += ['Included compartments: ' + '; '.join(i['name'] for i in covered) + '.', '']
            continue
        # Floor-installed variants share their loose counterpart's price and dry mass.
        shown = [i for i in covered if not i['installed']]
        for installed in (i for i in covered if i['installed']):
            loose = items[installed['id'].replace('Installed', 'Loose')]
            if (installed['massKg'], installed['baseValue']) != (loose['massKg'], loose['baseValue']):
                raise ValueError(f'Installed/loose valuation differs: {installed["id"]}; extend the renderer')
        def state(i):
            return group['labels'].get(i['id'], 'Damaged' if i['id'].endswith('Dmg') else 'Functional' if len(shown) == 2 and any(j['id'].endswith('Dmg') for j in shown) else 'Item / fresh template')
        rows = []
        for item in shown:
            dismantle = next((j for j in item['jobs'] if j['kind'] == 'dismantle'), None)
            rows.append((state(item), f'{item["massKg"]:g}', money(item['baseValue']),
                         money(sum(p['baseValue'] for p in dismantle['outputs'])) if dismantle else 'No mod-authored yield'))
        out += table(['Form / origin', 'Mass (kg)', 'Base (cr)', 'Dismantle outputs (cr)'], rows)
        out += ['In-game name' + ('s' if len({i['name'] for i in shown}) > 1 else '') + ': ' + '; '.join(dict.fromkeys(i['name'] for i in shown)) + '.', '']
        services = []
        for item in shown:
            for job in item['jobs']:
                if job['kind'] not in ('repair', 'restore', 'dismantle'): continue
                result = '; '.join(f'{p["count"]} × {p["name"]}' for p in job['outputs'])
                if job['kind'] == 'repair': result += '; actual consumed repair materials retained as spent parts'
                if job['kind'] == 'restore': result = 'Wear reduced in place; same item retained'
                services.append((job['kind'].capitalize() + ' — ' + state(item),
                                 '; '.join(material(x, config) for x in job['inputs']) or 'No replacement materials',
                                 ', '.join(config['triggers'][x] for x in job['tools']) or 'No specific tool in definition', result))
        if services:
            out += table(['Action / form', 'Consumed materials', 'Reusable tools', 'Result'], services)
        else:
            out += ['No mod-authored Repair, Restore or Dismantle action for this entry. This does not promise a native inherited action for a prototype or cargo item.', '']
        matches = {i['id']: state(i) for i in covered}
        for item in covered:
            matches.update({alias: state(item) for alias in item['aliases']})
        sources = set()
        for source in mod['sources']:
            if source['item'] not in matches: continue
            label = config['sources'].get(source['table'])
            if label is None and source['table'].startswith('ItmNavStationMods'):
                label = 'Damaged-only navigation-module pools' if source['table'].endswith('Dmg') else 'Mixed-condition navigation-module pools'
            if label is None: raise ValueError('Describe acquisition table: ' + source['table'])
            sources.add((label, source['condition'] if source['condition'] != 'Loot' else matches[source['item']],
                         f'{source["chance"] * 100:g}%', str(source['count'])))
        if sources:
            out += table(['Registered source', 'Offer / form', 'Chance per roll', 'Quantity'], sorted(sources))
        else:
            out += ['No direct added merchant/loot offer; use the production or historical route described above.', '']
    if mod['recipes']:
        out += ['## Construction and recovery', '',
                'Use an installed native Bar/Dining Table, or a supported optional workbench. Times are configured work minutes, excluding hauling, skills and interruptions. '
                'Tools are reusable requirements. These recipes are distinct from native INSTALL placement and from autonomous furnace/crop cycles.', '']
        for recipe in mod['recipes']:
            names = mod['recipeItemNames']
            out += [f'### {recipe["name"]}', '']
            out += table(['Consumed inputs', 'Physical outputs', 'Work (min)', 'Tools'], [(
                '; '.join(f'{i["count"]} × {names[i["item"]]}' for i in recipe['ingredients']),
                '; '.join(f'{i["count"]} × {names[i["item"]]}' for i in recipe['outputs']),
                f'{recipe["workSeconds"] / 60:g}', ', '.join(config['triggers'][x] for x in recipe['toolTriggers']))])
    out += ['## Evidence and upkeep', '',
            'Item names, dry/template masses, prices, service bills, salvage outputs, placement tabs, stock probabilities and table recipes are generated from current Phobos definitions. '
            '**Blue Bottle Games’ Ostranauts** native `DataCO.GetBasePrice` supplies the offline valuation used here '
            '([developer’s game page](https://bluebottlegames.com/games/ostranauts)). That page identifies the game; the actual numeric evidence is the locally inspected assembly, '
            'whose hash is retained in the generated data snapshot. No proprietary source or game assembly is distributed.', '',
            'Function/use explanations are maintained in the reviewed catalogue. All fictional prices, yields and simplified processing are Phobos gameplay choices. '
            'Research attribution remains beside the relevant claims in the linked operating/research guides. '
            'See [reference maintenance](item-reference-maintenance.md) for the one-click updater and coverage checks.', '']
    return '\n'.join(out)


def generate(root, data, config):
    mods = validate(data, config)
    outputs = {Path(f'docs/{SLUGS[mid]}-item-reference.md'): render(mod, config['mods'][mid], config)
               for mid, mod in mods.items()}
    index = ['# Phobos equipment and item references', '',
             'Choose your mod for what each object does, how to use it, where it appears, and its current base prices, repair bills and salvage outputs. '
             'Tables are generated from the current definitions; operating notes are reviewed separately.', '',
             '| Mod | Reference |', '| --- | --- |']
    index += [f'| {m["name"]} | [Items and equipment]({SLUGS[mid]}-item-reference.md) |' for mid, m in mods.items()]
    index += ['', 'Manufacturing is explicitly empty while it remains a scaffold. Framework documents shared spent parts; Approach Assist is labelled as a historical prototype.', '',
              'For placement tabs, see [INSTALL catalogue](install-catalogue.md). For refreshing these documents, see [reference maintenance](item-reference-maintenance.md).', '']
    outputs[Path('docs/item-references.md')] = '\n'.join(index)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--snapshot', type=Path, help='Fresh data-only export from the native audit')
    parser.add_argument('--check', action='store_true', help='Compare without changing tracked files')
    args = parser.parse_args()
    try:
        config = json.loads((ROOT / CONFIG).read_text(encoding='utf-8'))
        data = json.loads((args.snapshot or ROOT / SNAPSHOT).read_text(encoding='utf-8-sig'))
        hashes = source_hashes(ROOT)
        if args.snapshot:
            data['sourceHashes'] = hashes
        elif data.get('sourceHashes') != hashes:
            raise ValueError('Source changed since the native export. Run scripts/update-item-reference.ps1.')
        outputs = generate(ROOT, data, config)
        outputs[SNAPSHOT] = json.dumps(data, ensure_ascii=False, indent=2) + '\n'
        changed = [p for p, text in outputs.items() if not (ROOT / p).exists() or (ROOT / p).read_text(encoding='utf-8-sig') != text]
        if args.check and changed:
            raise ValueError('Stale item references: ' + ', '.join(map(str, changed)))
        if not args.check:
            # Render and validate every guide before replacing any file.
            for path in changed:
                (ROOT / path).write_text(outputs[path], encoding='utf-8', newline='\n')
        print(json.dumps({'status': 'valid', 'guides': len(outputs)-1, 'itemDefinitions': sum(len(m['items']) for m in data['mods']),
                          'changedFiles': list(map(str, changed)), 'mode': 'check' if args.check else 'update'}))
        return 0
    except (ValueError, KeyError, OSError) as exc:
        print('Item reference error: ' + str(exc), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
