<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Version>0.13.0</Version>
    <GameManaged>$(OstranautsPath)/Ostranauts_Data/Managed</GameManaged>
    <BepInExCore>$(OstranautsPath)/BepInEx/core</BepInExCore>
  </PropertyGroup>
  <Target Name="RequireLocalGame" BeforeTargets="ResolveReferences">
    <Error Condition="!Exists('$(GameManaged)/Assembly-CSharp.dll')" Text="Supply OstranautsPath for your local installation." />
    <Error Condition="!Exists('$(BepInExCore)/BepInEx.dll')" Text="The installation must contain BepInEx 5." />
  </Target>
  <ItemGroup>
    <ProjectReference Include="../PhobosFramework/PhobosFramework.csproj" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="$(GameManaged)/Assembly-CSharp.dll" Private="false" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="$(GameManaged)/Assembly-CSharp-firstpass.dll" Private="false" />
    <Reference Include="Newtonsoft.Json" HintPath="$(GameManaged)/Newtonsoft.Json.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(GameManaged)/UnityEngine.UI.dll" Private="false" />
    <Reference Include="UnityEngine.UIModule" HintPath="$(GameManaged)/UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(GameManaged)/Unity.TextMeshPro.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(GameManaged)/UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GameManaged)/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(GameManaged)/UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(GameManaged)/UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="BepInEx" HintPath="$(BepInExCore)/BepInEx.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(BepInExCore)/0Harmony.dll" Private="false" />
  </ItemGroup>
  <ItemGroup><EmbeddedResource Include="../../translations/PhobosShipbreaker/en.json" LogicalName="PhobosShipbreaker.en.json" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="../../mods/PhobosShipbreaker/framework/equipment-names.json" LogicalName="PhobosShipbreaker.equipment-names.json" /></ItemGroup>
</Project>
